version: '3.7'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=MongoBD2
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017